// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_26aa9e6ca21ef3a5, []int{0}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type BaseResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseResponse) Reset()         { *m = BaseResponse{} }
func (m *BaseResponse) String() string { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()    {}
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_26aa9e6ca21ef3a5, []int{1}
}
func (m *BaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResponse.Unmarshal(m, b)
}
func (m *BaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResponse.Marshal(b, m, deterministic)
}
func (dst *BaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResponse.Merge(dst, src)
}
func (m *BaseResponse) XXX_Size() int {
	return xxx_messageInfo_BaseResponse.Size(m)
}
func (m *BaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResponse proto.InternalMessageInfo

func (m *BaseResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BaseResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type User struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Logo                 string   `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_26aa9e6ca21ef3a5, []int{2}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

type LoginResponse struct {
	User                 *User         `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	BaseResp             *BaseResponse `protobuf:"bytes,255,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_26aa9e6ca21ef3a5, []int{3}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginResponse) GetBaseResp() *BaseResponse {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*BaseResponse)(nil), "user.BaseResponse")
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*LoginResponse)(nil), "user.LoginResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_26aa9e6ca21ef3a5) }

var fileDescriptor_user_26aa9e6ca21ef3a5 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0xc4, 0x40,
	0x0c, 0x85, 0xa9, 0x2d, 0x52, 0x63, 0x05, 0x99, 0xd3, 0xe0, 0x41, 0x64, 0x4e, 0x9e, 0x2a, 0xa8,
	0x3f, 0x40, 0x3c, 0x78, 0xf2, 0x34, 0xe0, 0xdd, 0x76, 0x1b, 0x4a, 0x61, 0xdb, 0x74, 0x27, 0x2d,
	0xfb, 0xf3, 0x77, 0x49, 0x66, 0xb6, 0xec, 0xed, 0x9b, 0x97, 0x97, 0xe4, 0x65, 0x00, 0x56, 0xc6,
	0x50, 0xcf, 0x81, 0x16, 0x32, 0x85, 0xb0, 0xfb, 0x81, 0xea, 0x97, 0xfa, 0x61, 0xf2, 0x78, 0x58,
	0x91, 0x17, 0xf3, 0x04, 0xa5, 0xe8, 0x53, 0x33, 0xa2, 0xcd, 0x5e, 0xb2, 0xd7, 0x3b, 0xbf, 0xbd,
	0xa5, 0x36, 0x37, 0xcc, 0x47, 0x0a, 0x9d, 0xbd, 0x89, 0xb5, 0xcb, 0xdb, 0x7d, 0x42, 0xf5, 0xdd,
	0x30, 0x7a, 0xe4, 0x99, 0x26, 0x46, 0x63, 0xa0, 0xd8, 0x51, 0x17, 0x67, 0xe4, 0x5e, 0xd9, 0x3c,
	0x42, 0x3e, 0x72, 0x9f, 0x5a, 0x05, 0xdd, 0x17, 0x14, 0x7f, 0x8c, 0x41, 0x2a, 0xeb, 0xd0, 0xa5,
	0x85, 0x82, 0xd2, 0xaf, 0x19, 0xa2, 0x59, 0x59, 0xb4, 0x3d, 0xf5, 0x64, 0xf3, 0xa8, 0x09, 0xbb,
	0x7f, 0x78, 0x48, 0xf9, 0xd3, 0xe2, 0x67, 0xd0, 0xc3, 0x74, 0xd6, 0xfd, 0x3b, 0xd4, 0x7a, 0xb1,
	0x2c, 0xf1, 0xaa, 0x9b, 0x37, 0x28, 0xdb, 0x14, 0xd4, 0x9e, 0xa2, 0xc9, 0x44, 0xd3, 0x75, 0x7e,
	0xbf, 0x99, 0xda, 0x5b, 0xfd, 0xae, 0x8f, 0x73, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x39, 0x5d,
	0x22, 0x3c, 0x01, 0x00, 0x00,
}
